name: Run Chef Cookstyle

on: push

jobs:
  chef_linter:
    name: Lint chef code using cookstyle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: Install cookstyle gem
      run: gem install cookstyle

    - name: Run cookstyle
      run: cookstyle . -a

    - name: Push code
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          exit 0
        fi
        git commit -m "Chef Cookstyle job"
        git push github HEAD:${GITHUB_REF}
      if: always()
