name: Run Chef Cookstyle
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: push

jobs:
  chef_linter:
    name: Lint chef code using cookstyle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: Install cookstyle gem
      run: gem install cookstyle

    - name: Run cookstyle
      run: cookstyle . -a

    - name: Promote code
      run: |
        git config --global user.name 'jajera'
        git config --global user.email 'jajera@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Chef Cookstyle job"
        git push
